sudo: required
dist: trusty

cache:
  pip: false 

env:
  matrix:
    - LINT=vimlint-errors
    - LINT=vimlint

matrix:
  allow_failures:
    - env: LINT=vimlint

install:
  - |
    if [ "${LINT#vimlint}" != "$LINT" ]; then
      git clone --depth=1 https://github.com/syngan/vim-vimlint /tmp/vimlint
      git clone --depth=1 https://github.com/ynkdir/vim-vimlparser /tmp/vimlparser
    fi
script:
  - |
    if [ "$LINT" = "vimlint" ]; then
      sh /tmp/vimlint/bin/vimlint.sh  -l /tmp/vimlint  -p /tmp/vimlparser .
    elif [ "$LINT" = "vimlint-errors" ]; then
      sh /tmp/vimlint/bin/vimlint.sh  -E -l /tmp/vimlint -p /tmp/vimlparser .
    fi
